In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns

In [3]:
df=pd.read_csv('data\stud.csv')

In [4]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

data checks
1 check missing values
2 check duplicates
3 check data types
4 check the no of unique values of each column
5 check statistics of dataset
6 check various categories present in different categorical column

In [5]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

# no missing values in dataset

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [8]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [9]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [11]:
print(f"categories in gender variable : {df['gender'].unique()} and sum: {df['gender'].nunique()}")
print(f"categories in race_ethnicity variable : {df['race_ethnicity'].unique()} and sum= {df['race_ethnicity'].nunique()}")
print(f"categories in parental_level_of_education variable : {df['parental_level_of_education'].unique()} and sum : {df['parental_level_of_education'].nunique()}")
print(f"categories in lunch : {df['lunch'].unique()} and sum : {df['lunch'].nunique()}")
print(f"categories in test_prepration_course : {df['test_preparation_course'].unique()} and sum : {df['test_preparation_course'].nunique()}")

categories in gender variable : ['female' 'male'] and sum: 2
categories in race_ethnicity variable : ['group B' 'group C' 'group A' 'group D' 'group E'] and sum= 5
categories in parental_level_of_education variable : ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school'] and sum : 6
categories in lunch : ['standard' 'free/reduced'] and sum : 2
categories in test_prepration_course : ['none' 'completed'] and sum : 2

In [12]:
numerical_features=df.select_dtypes(include='number').columns.tolist()
categorical_features=df.select_dtypes(exclude='number').columns.tolist()


print(f"num of categorical features : {len(categorical_features)}  and they are :{categorical_features}")
print(f"num of numerical features : {len(numerical_features)}  and they are :{numerical_features}")

num of categorical features : 5  and they are :['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
num of numerical features : 3  and they are :['math_score', 'reading_score', 'writing_score']

In [13]:
df['total_score']=df['math_score']+df['reading_score']+df['writing_score']
df['average']=df['total_score']/3
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [14]:
reading_full=df[df['reading_score']==100].shape[0]
writing_full=df[df['writing_score']==100].shape[0]
math_full=df[df['math_score']==100].shape[0]
print(f"students with full reading score : {reading_full}")
print(f"students with full writing score : {writing_full}")
print(f"students with full math score : {math_full}")

students with full reading score : 17
students with full writing score : 14
students with full math score : 7

In [15]:
reading_lessthan_20=df[df['reading_score']<=20].shape[0]
writing_lessthan_20=df[df['writing_score']<=20].shape[0]
math_lessthan_20=df[df['math_score']<=20].shape[0]
print(f"students with less than 20 reading score : {reading_lessthan_20}")
print(f"students with less than 20 writing score : {writing_lessthan_20}")
print(f"students with less than 20 math score : {math_lessthan_20}")

students with less than 20 reading score : 1
students with less than 20 writing score : 3
students with less than 20 math score : 4